apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  namespace: standard
spec:
  ingressClassName: traefik
  rules:
  - host: exam.kub.boudun.cloudns.ph
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
             service:
              name: fastapi-service
              port:
                number: 80
        - path: /pgadmin
          pathType: Prefix
          backend:
             service:
              name: pgadmin-service
              port:
                number: 8080