apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize

secretGenerator:
  - name: secrets-postgre-creds
    literals:
      - pgs-password="cGFzc3dvcmQ="
      - pga-password="cm9vdA=="

resources:
  - storage.yaml
  - bdd.yaml
  - pgadmin.yaml
  - fastapi.yaml
  - hpa.yaml
  - clusterissuer.yaml
  - ingress.yaml