# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize

resources:
  - ../YAML-STANDARD/

secretGenerator:
  - name: secrets-postgre-creds
    literals:
      - pgs-password="cGFzc3dvcmQ="
      - pga-password="cm9vdA=="