apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.bdd.name}}-statefulset
  namespace: {{.Values.namespace.name}}
spec:
  serviceName: "{{.Values.bdd.name}}-service"
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.bdd.name}}
  template:
    metadata:
      labels:
        app: {{.Values.bdd.name}}
    spec:
      containers:
      - name: {{.Values.bdd.name}}
        image: {{.Values.bdd.image.repository}}:{{.Values.bdd.image.tag}}
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{.Values.secrets.name}}
              key: pgs-password
        - name: POSTGRES_DB
          value: storedb
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
        - containerPort: {{.Values.bdd.service.port}}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{.Values.storage.name}}
---          
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.bdd.name}}
  namespace: {{.Values.namespace.name}}
spec:
  selector:
    app: {{.Values.bdd.name}}
  ports:
    - protocol: TCP
      port: {{.Values.bdd.service.port}}
      targetPort: {{.Values.bdd.service.port}}