apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.clusterissuer.name}}
  namespace: {{.Values.namespace.name}}
spec:
  acme:
    server: {{.Values.clusterissuer.server}}
    email: {{.Values.clusterissuer.email}}
    privateKeySecretRef:
      name: {{.Values.clusterissuer.name}}
    solvers:
    - http01:
        ingress:
          class: traefik