apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.storage.name}}
  namespace: {{.Values.namespace.name}}
spec:
  accessModes:
    - {{.Values.storage.spec.accessModes}}
  resources:
    requests:
      storage: {{.Values.storage.spec.size}}
