apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: standard
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: duncan.boutet@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-yaml
    solvers:
    - http01:
        ingress:
          class: traefik